from .user_views import UserCreateView, UserDetailUpdateDeleteView, AddRolToUserView, RemoveRolFromUserView
from .rol_views import ListCreateRolView, DeleteRolView, AddPermissionToRolView, RemovePermissionFromRolView
from .permission_views import ListCreatePermissionView, DeletePermissionView